// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAFIRTrC5oumYXG7X5ECnjucTiVnkeyH8',
    appId: '1:405907197709:web:f6445a746f4c51f9252a44',
    messagingSenderId: '405907197709',
    projectId: 'dating-e74fa',
    authDomain: 'dating-e74fa.firebaseapp.com',
    storageBucket: 'dating-e74fa.appspot.com',
    measurementId: 'G-F9KM2KF0D2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAquwFLnkQYnGh3AAgKUlEmJ5XKqk1aP6s',
    appId: '1:405907197709:android:dc59c27c3cbe20e1252a44',
    messagingSenderId: '405907197709',
    projectId: 'dating-e74fa',
    storageBucket: 'dating-e74fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAiB9rCFerPpxV0o-s_FxLPr1Yf6FKTHU',
    appId: '1:405907197709:ios:0e1d2a9b90f47901252a44',
    messagingSenderId: '405907197709',
    projectId: 'dating-e74fa',
    storageBucket: 'dating-e74fa.appspot.com',
    iosBundleId: 'com.example.dating',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAiB9rCFerPpxV0o-s_FxLPr1Yf6FKTHU',
    appId: '1:405907197709:ios:d2ca190374bd5ea7252a44',
    messagingSenderId: '405907197709',
    projectId: 'dating-e74fa',
    storageBucket: 'dating-e74fa.appspot.com',
    iosBundleId: 'com.example.dating.RunnerTests',
  );
}
